# Generated by Django 5.0 on 2024-01-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='price',
            field=models.FloatField(),
        ),
    ]
