# Generated by Django 5.0 on 2024-02-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_breakfast_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField()),
                ('del_price', models.IntegerField(blank=True, null=True)),
                ('ball', models.IntegerField()),
                ('review', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField()),
                ('del_price', models.IntegerField(blank=True, null=True)),
                ('ball', models.IntegerField()),
                ('review', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField()),
                ('del_price', models.IntegerField(blank=True, null=True)),
                ('ball', models.IntegerField()),
                ('review', models.IntegerField()),
            ],
        ),
    ]
